name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Docker build
      run: |
        docker build -t test-image .
        
    - name: Test TA-Lib import
      run: |
        docker run --rm test-image python -c "import talib; print('✅ TA-Lib OK:', talib.__version__)"
        
    - name: Test bot imports
      run: |
        docker run --rm test-image python -c "
        import sys
        sys.path.append('/app')
        try:
            from rsi_strategy import RSIStrategyBase
            print('✅ RSI Strategy OK')
        except ImportError as e:
            print('❌ Import error:', e)
            sys.exit(1)
        "

